openapi: 3.1.0
info:
  title: TD OpenAPI Specification - Exercise 1
  description: Ping pong
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
paths:
  /ping:
    get:
      description: Return pong.
      responses:
        '200':
          description: Ok
          content:
            text/plain:
              schema:
                type: string
                example: pong
  
