openapi: 3.1.0
info:
  title: TD OpenAPI Specification - Exercise 3
  description: Tasks management
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
paths:
  /tasks:
    get:
      responses:
        '200':
          description: return tasks list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Task'
      responses:
        '201':
          description: return new tasks list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
    delete:
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
      responses:
        '200':
          description: return deleted tasks list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'

  /tasks/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: return task with the id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '404':
          description: no task found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: no task found
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: return deleted task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        completed:
          type: boolean
