openapi: 3.1.0
info:
  title: TD OpenAPI Specification - Exercise 4
  description: Products search API
  version: 1.0.0
servers:
  - url: 'http://localhost:8000'
paths:
  /products:
    get:
      parameters:
        - $ref: '#/components/parameters/LimitParam'
        - $ref: '#/components/parameters/QParam'
      responses:
        '200':
          description: products list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                multipleProducts:
                  value:
                    - name: "Cookies"
                      expiration_datetime: "2025-09-01T12:00:00Z"
                      price: 2500
                    - name: "Kiwi"
                      expiration_datetime: "2025-09-05T18:00:00Z"
                      price: 1200
                    - name: "Water"
                      expiration_datetime: "2025-10-15T16:00:00Z"
                      price: 1100
                emptyList:
                  value: []

components:
  parameters:
    LimitParam:
      name: limit
      in: query
      schema:
        type: integer
      example: 10
    QParam:
      name: q
      in: query
      schema:
        type: string
      example: "kiwi"
  schemas:
    Product:
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float